version: "3.8"

services:
  mongo-1:
    image: mongo:4
    networks:
      - mongodb
    volumes:
      - type: volume
        source: mongo-1-data
        target: /data/db
    command: --replSet testRS --storageEngine wiredTiger
  mongo-2:
    image: mongo:4
    networks:
      - mongodb
    volumes:
      - type: volume
        source: mongo-2-data
        target: /data/db
    command: --replSet testRS --storageEngine wiredTiger
  mongo-3:
    image: mongo:4
    networks:
      - mongodb
    volumes:
      - type: volume
        source: mongo-3-data
        target: /data/db
    command: --replSet testRS --storageEngine wiredTiger
  mongo-initializer:
    depends_on:
      - mongo-1
      - mongo-2
      - mongo-3
    image: mongo:4
    networks:
      - mongodb
    volumes:
      - type: bind
        source: ./rs.js
        target: /rs.js
    entrypoint: mongo mongo-1:27017 --quiet /rs.js

networks:
  mongodb:

volumes:
  mongo-1-data:
  mongo-2-data:
  mongo-3-data:
